# BLU02 - Learning Notebook - Data wrangling workflows - Part 1 of 3

In [22]:
import numpy as np
import pandas as pd
import os

from sklearn.datasets import load_iris

# About the BLU 

## Data wrangling workflows

A typical data science workflow goes as follows: you get data from a source, you clean it, and then you continuously iterate on it.

![data_transformation_workflow](./media/data_processing_workflow.png)

On the previous learning unit in this specialization, we focused mostly on getting and cleaning data (the blue boxes above). 

At this point, we got a dataset and performed necessary data cleaning. Our data is, therefore, in an interim state:
* You have a *tidy dataset* (observations as rows and features as columns), comprised of one or more tables
* You know how to import such tables into Pandas, regardless of the format they are stored.

Now, to explore, visualize and model the data, we have to perform transformations on it with agility, balancing:
* Speed of iteration, testing different hypothesis fast and easy
* Consistency, ensuring our pipeline doesn't collapse along the way.

In this first part, we'll go into how to transform the dataset and explore it in Pandas.

Then, we'll zoom in on a how to combine dataframes.

Finally, we'll move to scikit-learn to build efficient pipelines for modeling.

# About the data

The New York Philharmonic played its first concert on December 7, 1842.

The data documents all known concerts, amounting to more than 20,000 performances. Some considerations:
* The Program is the top-most level element in the dataset
* A Program is defined as performances in which the repertoire, conductors, and soloists are the same
* A Program is associated with an Orchestra (e.g., New York Philharmonic) and a Season (e.g., 1842-43)
* A Program may have multiple Concerts with different dates, times and locations
* A Program's repertoire may contain various Works (e.g., two different symphonies by Beethoven)
* A Work can have multiple Soloists (e.g., Mahler on the harpsichord, Strauss or Bernstein on the piano).

**For more information about the dataset, including the data dictionary, please head to the README.**

In this unit, we will be using Works and Concerts, imported as follows.

In [23]:
works = pd.read_csv('./data/works.csv')
concerts = pd.read_csv('./data/concerts.csv')

In [24]:
works.head()

,GUID,ProgramID,WorkID,MovementID,ComposerName,WorkTitle,Movement,ConductorName,Interval
0,38e072a7-8fc9-4f9a-8eac-3957905c0002,3853,52446,NaN,"Beethoven, Ludwig van","SYMPHONY NO. 5 IN C MINOR, OP.67",NaN,"Hill, Ureli Corelli",NaN
1,c7b2b95c-5e0b-431c-a340-5b37fc860b34,5178,52437,NaN,"Beethoven, Ludwig van","SYMPHONY NO. 3 IN E FLAT MAJOR, OP. 55 (EROICA)",NaN,"Hill, Ureli Corelli",NaN
2,894e1a52-1ae5-4fa7-aec0-b99997555a37,10785,52364,1.0,"Beethoven, Ludwig van","EGMONT, OP.84",Overture,"Hill, Ureli Corelli",NaN
3,34ec2c2b-3297-4716-9831-b538310462b7,5887,52434,NaN,"Beethoven, Ludwig van","SYMPHONY NO. 2 IN D MAJOR, OP.36",NaN,"Boucher, Alfred",NaN
4,610a4acc-94e4-4cd6-bdc1-8ad020edc7e9,305,52453,NaN,"Beethoven, Ludwig van","SYMPHONY NO. 7 IN A MAJOR, OP.92",NaN,"Hill, Ureli Corelli",NaN

In [37]:
concerts.head()

,GUID,ProgramID,ConcertID,EventType,Location,Venue,Date,Time
0,38e072a7-8fc9-4f9a-8eac-3957905c0002,3853,0,Subscription Season,"Manhattan, NY",Apollo Rooms,1842-12-07T05:00:00+00:00,8:00PM
1,c7b2b95c-5e0b-431c-a340-5b37fc860b34,5178,0,Subscription Season,"Manhattan, NY",Apollo Rooms,1843-02-18T05:00:00+00:00,8:00PM
2,894e1a52-1ae5-4fa7-aec0-b99997555a37,10785,0,Special,"Manhattan, NY",Apollo Rooms,1843-04-07T05:00:00+00:00,8:00PM
3,34ec2c2b-3297-4716-9831-b538310462b7,5887,0,Subscription Season,"Manhattan, NY",Apollo Rooms,1843-04-22T05:00:00+00:00,8:00PM
4,610a4acc-94e4-4cd6-bdc1-8ad020edc7e9,305,0,Subscription Season,"Manhattan, NY",Apollo Rooms,1843-11-18T05:00:00+00:00,NaN

# 1 Data transformation

## 1.1 Transformations as functions 

Most data transformations operate on dataframes: they receive a local dataframe, transform it and return a new one.

In its simplest form, this is the signature of a generic data transformer.

In [26]:
def data_transformer(df):
    df = df.copy()
    # df = ...
    return df

Such transformations have no side effects and operate as functions on immutable data (i.e., they keep the original dataframe unchanged).

Since the output depends only on the arguments, calling them with the same arguments always produces the same result.

Confusing? Not really.

In [27]:
def rename_column(df, new_name, old_name):
    df = df.copy()
    df[new_name] = df[old_name]
    df = df.drop(columns=old_name)
    return df

def test_dataframe():
    data = np.random.randn(6, 4)
    columns = ['A', 'B', 'C', 'D']
    return pd.DataFrame(data=data, columns=columns)

df = test_dataframe()

rename_column(df, 'Z', 'A')

          B         C         D         Z
0  0.671705  0.898021 -0.762391  1.052322
1 -1.636238  0.045260  0.018398  0.521242
2  1.113846 -0.568521  0.253791  0.088525
3 -0.904122 -0.482147 -1.147494 -0.270436
4 -0.259586 -0.634578 -0.068726 -0.684142
5  0.621898  1.257558  0.941698  0.348890

In [28]:
rename_column(df, 'Z', 'A')

          B         C         D         Z
0  0.671705  0.898021 -0.762391  1.052322
1 -1.636238  0.045260  0.018398  0.521242
2  1.113846 -0.568521  0.253791  0.088525
3 -0.904122 -0.482147 -1.147494 -0.270436
4 -0.259586 -0.634578 -0.068726 -0.684142
5  0.621898  1.257558  0.941698  0.348890

The same result, see! The program (or Notebook) remembers nothing but the original data and the function itself: a white canvas!

What about the original dataframe?

In [29]:
df

          A         B         C         D
0  1.052322  0.671705  0.898021 -0.762391
1  0.521242 -1.636238  0.045260  0.018398
2  0.088525  1.113846 -0.568521  0.253791
3 -0.270436 -0.904122 -0.482147 -1.147494
4 -0.684142 -0.259586 -0.634578 -0.068726
5  0.348890  0.621898  1.257558  0.941698

After each call, the program *state* is the same as it was before (no new objects, no changes, no nothing!), as if nothing happened.

This property is valid for as long as we don't explicitly overwrite the original dataframe outside the function, using an assignment.

In [30]:
df = test_dataframe()
df = rename_column(df, 'Z', 'A')

try:
    rename_column(df, 'Z', 'A')
except:
    print("For some reason this doesn't work. Why is that?")

For some reason this doesn't work. Why is that?

Mutable data is dangerous because it makes programs unpredictable. And this is why you should avoid modifying objects after creation.

Such pitfall is common in Notebooks, especially when you re-run cells, run them in a different order or restart the Kernel. (Am I right?)

**Data transformation is a *pipeline***

Another problem is that data transformation is about applying multiple, sequential changes to the data (i.e., a multistep process).

![data_transformation_pipeline](./media/data_transformation_pipeline.png)

*Fig 2. - A data transformation pipeline is a multistep process.*

And once we realize this, how do we go about it?

In [31]:
df = test_dataframe()

df_renamed = rename_column(df, 'Z', 'A')
# Code happens. Ideas are tested, hours go by.
df_renamed_without_b = df_renamed.drop(columns='B')
# More code happens. We keep on testing ideas, days go by.
df_renamed_without_b_positive = df_renamed_without_b[df_renamed_without_b > 0]
# There's a lot of code. Ideas come and go, we've been doing this for a week.
df_renamed_without_b_positive_no_nans = df_renamed_without_b_positive.dropna(how='all')
# Can we honestly trace back how to get from df to here? Probably not.
df_renamed_without_b_positive_no_nans

          C         D         Z
0  0.514465       NaN       NaN
1       NaN  0.472815  1.299376
2       NaN  0.171529       NaN
3  0.782010       NaN       NaN
4  0.027408  0.465358  0.752623
5  0.329960       NaN  0.873309

Using functions instead, you concisely encapsulate everything. 

(Also, you spend less time naming things, unless you want to.)

In [32]:
def data_transformer(df, how_to_dropna):
    df = df.copy()
    df = rename_column(df, 'Z', 'A')
    df = df.drop(columns='B')
    df = df[df > 0]
    df = df.dropna(how=how_to_dropna)
    return df

data_transformer(df, how_to_dropna='all')

          C         D         Z
0  0.514465       NaN       NaN
1       NaN  0.472815  1.299376
2       NaN  0.171529       NaN
3  0.782010       NaN       NaN
4  0.027408  0.465358  0.752623
5  0.329960       NaN  0.873309

This function is a bad one: names are not explicit, and there are no apparent blocks of logic.

Functions should organize and document our codebase (*what* you are doing and how).

Using functions, immutable data and avoiding side effects is a smart choice to manage complexity and keep things understandable.

Alternatively, we could structure our functions more like this.

In [33]:
def preprocess_data():
    df = df.copy()
    # df = rename_misspelled_columns(df)
    # df = drop_unnecessary_columns(df)
    # df = keep_only_positive_values(df)
    # df = removemissing_values(df)
    return df

## 1.2 Data transformation in Pandas

Pandas provides convenient methods for most data transformation tasks, with a unified, well-known syntax and consistent interfaces.

For example, we don't need to create a `rename_column()` function, since Pandas already provides a `df.rename()` method for us.

In [34]:
df = test_dataframe()

df.rename({'A': 'Z'}, axis=1)

          Z         B         C         D
0 -1.115534 -0.752959  0.313357  0.604778
1  0.555831  1.550978  1.447116  0.976282
2 -0.339139 -0.722698  0.877912  0.495573
3 -0.046894  1.044629  0.207771  0.589219
4 -0.147292 -0.964560  1.136206  0.038622
5 -0.523218  0.105360 -1.214892  0.231231

As a recap: `df.rename()` follows our transformer signature:
* It takes a dataframe as input 
* And returns a new one as output.

This predictable input/output is what we mean by consistent interfaces! 

It seems very promising to build and multistep pipelines, no? What transformations can we perform this way?

### 1.2.1 Subsetting columns or the index

#### Take a subset of indexes or columns

Pandas implements this functionality, somewhat counterintuitively, as `df.filter()`.

Imagine that we want only the columns related to the work itself, excluding IDs.

In [35]:
work_related_columns = ['ComposerName', 'WorkTitle', 'Movement']
# Select columns by name.
works.filter(items=work_related_columns).head()

,ComposerName,WorkTitle,Movement
0,"Beethoven, Ludwig van","SYMPHONY NO. 5 IN C MINOR, OP.67",NaN
1,"Beethoven, Ludwig van","SYMPHONY NO. 3 IN E FLAT MAJOR, OP. 55 (EROICA)",NaN
2,"Beethoven, Ludwig van","EGMONT, OP.84",Overture
3,"Beethoven, Ludwig van","SYMPHONY NO. 2 IN D MAJOR, OP.36",NaN
4,"Beethoven, Ludwig van","SYMPHONY NO. 7 IN A MAJOR, OP.92",NaN

We can also use it to subset our dataframe based on the index.

In [36]:
# Select rows containing 'Glass' on the index.
works.set_index('ComposerName').filter(like='Glass', axis=0).reset_index().head()

,ComposerName,GUID,ProgramID,WorkID,MovementID,WorkTitle,Movement,ConductorName,Interval
0,"Glass, Philip",cf230066-2cd2-4093-8b78-b91b8dda3cbf,11639,5729,NaN,KOYAANISQATSI,NaN,"Riesman, Michael",NaN
1,"Glass, Philip",adf68bf5-db9d-4b24-aac6-c9b7c398cf06,14047,12401,NaN,"""FATHER DEATH BLUES"" FROM HYDROGEN JUKEBOX",NaN,"Sainte-Agathe, Valérie",NaN
2,"Glass, Philip",990a8f66-cd5f-466e-b3b6-800baa6c0b47-0.1,14189,12547,NaN,"QUARTET, STRING, NO. 3 (MISHIMA)",NaN,NaN,NaN
3,"Glass, Philip",3d50968c-2e8b-405f-969c-ba36f941f393,14189,12547,NaN,"QUARTET, STRING, NO. 3 (MISHIMA)",NaN,NaN,NaN
4,"Glass, Philip",fb8e7125-7ef9-492e-a820-914467475701,14025,12327,NaN,SARABANDE IN COMMON TIME (SOLO VIOLIN),NaN,NaN,NaN

### 1.2.2 Drop columns

Additionally, `GUID` and `ProgramID` are pretty redundant. We can get rid of `GUID`.

In [16]:
works.drop(columns='GUID').head()

,ProgramID,WorkID,MovementID,ComposerName,WorkTitle,Movement,ConductorName,Interval
0,3853,52446,NaN,"Beethoven, Ludwig van","SYMPHONY NO. 5 IN C MINOR, OP.67",NaN,"Hill, Ureli Corelli",NaN
1,5178,52437,NaN,"Beethoven, Ludwig van","SYMPHONY NO. 3 IN E FLAT MAJOR, OP. 55 (EROICA)",NaN,"Hill, Ureli Corelli",NaN
2,10785,52364,1.0,"Beethoven, Ludwig van","EGMONT, OP.84",Overture,"Hill, Ureli Corelli",NaN
3,5887,52434,NaN,"Beethoven, Ludwig van","SYMPHONY NO. 2 IN D MAJOR, OP.36",NaN,"Boucher, Alfred",NaN
4,305,52453,NaN,"Beethoven, Ludwig van","SYMPHONY NO. 7 IN A MAJOR, OP.92",NaN,"Hill, Ureli Corelli",NaN

### 1.2.3 Group By

This is a very extensive topic, and we'll just touch it's surface here, so that you know that exists and can explore it further later by your own.

In case you've worked with SQL before, you'll find this very familiar :)

So, in Pandas there is a process of three chained steps called split-apply-combine:

- split: splitting the DataFrame into groups (this is the groupby), we need to specify the column or the columns that will be used to form the groups.
- apply: apply a function to each group (aggregation, transformation and filtration)
- combine: create a DataFrame with the results

With this out of the way, it's time to focus on three types of functions you may want to apply:
* Aggregation (e.g., sum, count, mean)
* Transformation (e.g., filling missing values)
* Filtration (e.g., discard data from underrepresented groups).

We will drill-down into each one of them. For this next part, we will use be using the `concerts` data.

**Aggregation** (e.g., sum, count, mean)

We want to start by uncovering the most popular programs, by the number of performances.

So the first step is to group our data by `ProgramID`. This returns a DataFrameGroupBy object that by itself doesn't tell us much.

However, we can use the group property of the DataFrameGroupBy object to inspect the groups.

In [17]:
concerts_grouped_by_ProgramID = concerts.groupby('ProgramID')
concerts_grouped_by_ProgramID

In [18]:
concerts_grouped_by_ProgramID.groups

{1: Int64Index([474, 14097], dtype='int64'),
 2: Int64Index([1578], dtype='int64'),
 3: Int64Index([1579], dtype='int64'),
 4: Int64Index([1580, 14382], dtype='int64'),
 5: Int64Index([10075], dtype='int64'),
 6: Int64Index([1581], dtype='int64'),
 7: Int64Index([10076, 16815, 19224, 20893], dtype='int64'),
 8: Int64Index([10066], dtype='int64'),
 9: Int64Index([9471], dtype='int64'),
 10: Int64Index([7565], dtype='int64'),
 11: Int64Index([1582], dtype='int64'),
 12: Int64Index([10077, 16816, 19225, 20894], dtype='int64'),
 13: Int64Index([10058], dtype='int64'),
 14: Int64Index([9473], dtype='int64'),
 15: Int64Index([7566], dtype='int64'),
 16: Int64Index([154], dtype='int64'),
 17: Int64Index([3797, 14812], dtype='int64'),
 18: Int64Index([1583], dtype='int64'),
 19: Int64Index([10065], dtype='int64'),
 20: Int64Index([10078, 16817, 19226], dtype='int64'),
 21: Int64Index([9475], dtype='int64'),
 22: Int64Index([7567, 15738], dtype='int64'),
 24: Int64Index([1584], dtype='int64'),
 25: Int64Index([10063], dtype='int64'),
 26: Int64Index([10433], dtype='int64'),
 27: Int64Index([7568], dtype='int64'),
 28: Int64Index([1585, 14383], dtype='int64'),
 29: Int64Index([3799, 14813], dtype='int64'),
 30: Int64Index([10434], dtype='int64'),
 31: Int64Index([8604, 16117, 18674], dtype='int64'),
 32: Int64Index([7570, 15739], dtype='int64'),
 33: Int64Index([3800, 14814], dtype='int64'),
 34: Int64Index([4466], dtype='int64'),
 35: Int64Index([1589], dtype='int64'),
 36: Int64Index([10244], dtype='int64'),
 37: Int64Index([10435, 16978, 19355, 20978], dtype='int64'),
 38: Int64Index([8605], dtype='int64'),
 39: Int64Index([7571, 15740], dtype='int64'),
 40: Int64Index([4467, 14985, 18285], dtype='int64'),
 41: Int64Index([3801, 14815], dtype='int64'),
 42: Int64Index([334], dtype='int64'),
 43: Int64Index([1164], dtype='int64'),
 44: Int64Index([10436, 16979, 19356, 20979], dtype='int64'),
 45: Int64Index([8606, 16118], dtype='int64'),
 46: Int64Index([7572, 15741], dtype='int64'),
 47: Int64Index([19], dtype='int64'),
 48: Int64Index([4470, 14986, 18286], dtype='int64'),
 49: Int64Index([3803, 14816], dtype='int64'),
 50: Int64Index([1165, 14308], dtype='int64'),
 51: Int64Index([9549], dtype='int64'),
 52: Int64Index([10437, 16980, 19357], dtype='int64'),
 53: Int64Index([7573], dtype='int64'),
 54: Int64Index([1168], dtype='int64'),
 55: Int64Index([4472, 14987], dtype='int64'),
 56: Int64Index([3805, 14817], dtype='int64'),
 57: Int64Index([5101, 15174], dtype='int64'),
 58: Int64Index([9331, 16496, 18968, 20712], dtype='int64'),
 59: Int64Index([10439, 16981, 19358], dtype='int64'),
 60: Int64Index([7574], dtype='int64'),
 61: Int64Index([1169], dtype='int64'),
 62: Int64Index([4474], dtype='int64'),
 63: Int64Index([5103], dtype='int64'),
 64: Int64Index([9332], dtype='int64'),
 65: Int64Index([9218], dtype='int64'),
 66: Int64Index([7035, 15632], dtype='int64'),
 67: Int64Index([5104, 15175], dtype='int64'),
 68: Int64Index([4592, 15040, 18299], dtype='int64'),
 69: Int64Index([4475, 14988, 18287], dtype='int64'),
 70: Int64Index([312], dtype='int64'),
 71: Int64Index([1170, 14309, 18202], dtype='int64'),
 72: Int64Index([9333, 16497, 18969], dtype='int64'),
 73: Int64Index([9219], dtype='int64'),
 74: Int64Index([7036], dtype='int64'),
 75: Int64Index([5106], dtype='int64'),
 76: Int64Index([107], dtype='int64'),
 78: Int64Index([9334], dtype='int64'),
 79: Int64Index([9220], dtype='int64'),
 80: Int64Index([7037], dtype='int64'),
 81: Int64Index([5107, 15176], dtype='int64'),
 82: Int64Index([1179], dtype='int64'),
 83: Int64Index([9335, 16498, 18970], dtype='int64'),
 84: Int64Index([7038, 15633], dtype='int64'),
 85: Int64Index([1180, 14311], dtype='int64'),
 86: Int64Index([5109], dtype='int64'),
 87: Int64Index([9337, 16499, 18971, 20713], dtype='int64'),
 88: Int64Index([7039], dtype='int64'),
 89: Int64Index([5111, 15177], dtype='int64'),
 90: Int64Index([1876], dtype='int64'),
 91: Int64Index([7561], dtype='int64'),
 92: Int64Index([7040], dtype='int64'),
 93: Int64Index([7028], dtype='int64'),
 94: Int64Index([6722], dtype='int64'),
 95: Int64Index([5112], dtype='int64'),
 96: Int64Index([3031], dtype='int64'),
 97: Int64Index([1877], dtype='int64'),
 98: Int64Index([7042, 15634], dtype='int64'),
 99: Int64Index([6723], dtype='int64'),
 100: Int64Index([5113, 15178], dtype='int64'),
 101: Int64Index([1880], dtype='int64'),
 102: Int64Index([7044], dtype='int64'),
 103: Int64Index([6724, 15557], dtype='int64'),
 104: Int64Index([2722], dtype='int64'),
 105: Int64Index([1881, 14431], dtype='int64'),
 106: Int64Index([10431], dtype='int64'),
 107: Int64Index([8978, 16327, 18832, 20635], dtype='int64'),
 108: Int64Index([7045, 15635], dtype='int64'),
 109: Int64Index([6725], dtype='int64'),
 110: Int64Index([5922, 15370], dtype='int64'),
 111: Int64Index([2723], dtype='int64'),
 112: Int64Index([7046], dtype='int64'),
 113: Int64Index([1883], dtype='int64'),
 114: Int64Index([8979], dtype='int64'),
 115: Int64Index([6726], dtype='int64'),
 116: Int64Index([2724, 14564], dtype='int64'),
 117: Int64Index([5923], dtype='int64'),
 118: Int64Index([7047], dtype='int64'),
 119: Int64Index([1886], dtype='int64'),
 120: Int64Index([8980, 16328, 18833, 20636], dtype='int64'),
 121: Int64Index([6727], dtype='int64'),
 122: Int64Index([3622, 14766], dtype='int64'),
 123: Int64Index([2727], dtype='int64'),
 124: Int64Index([1887], dtype='int64'),
 125: Int64Index([5924], dtype='int64'),
 126: Int64Index([8981, 16329, 18834], dtype='int64'),
 127: Int64Index([6728], dtype='int64'),
 128: Int64Index([2728, 14566], dtype='int64'),
 129: Int64Index([5925, 15371], dtype='int64'),
 130: Int64Index([1888, 14432], dtype='int64'),
 131: Int64Index([9433], dtype='int64'),
 132: Int64Index([8984, 16330, 18835], dtype='int64'),
 133: Int64Index([3631], dtype='int64'),
 134: Int64Index([6729], dtype='int64'),
 135: Int64Index([1890], dtype='int64'),
 136: Int64Index([2730], dtype='int64'),
 137: Int64Index([3632, 14767], dtype='int64'),
 138: Int64Index([5927], dtype='int64'),
 139: Int64Index([9434], dtype='int64'),
 140: Int64Index([8985], dtype='int64'),
 141: Int64Index([6730], dtype='int64'),
 142: Int64Index([5928, 15372], dtype='int64'),
 143: Int64Index([3927], dtype='int64'),
 144: Int64Index([3633, 14768], dtype='int64'),
 145: Int64Index([2731], dtype='int64'),
 146: Int64Index([9435], dtype='int64'),
 147: Int64Index([7030], dtype='int64'),
 148: Int64Index([3634, 14769, 18217], dtype='int64'),
 149: Int64Index([2733], dtype='int64'),
 150: Int64Index([5929, 15373], dtype='int64'),
 151: Int64Index([9436], dtype='int64'),
 152: Int64Index([3636, 14770], dtype='int64'),
 153: Int64Index([2734, 14568], dtype='int64'),
 154: Int64Index([10304, 16913, 19303, 20945], dtype='int64'),
 155: Int64Index([5931], dtype='int64'),
 156: Int64Index([9437], dtype='int64'),
 157: Int64Index([3637], dtype='int64'),
 158: Int64Index([5932, 15374, 18326], dtype='int64'),
 159: Int64Index([9438], dtype='int64'),
 160: Int64Index([10306, 16914, 19304, 20946], dtype='int64'),
 161: Int64Index([8303, 15956, 18551, 20449], dtype='int64'),
 162: Int64Index([10308, 16915, 19305], dtype='int64'),
 163: Int64Index([5264], dtype='int64'),
 164: Int64Index([9439], dtype='int64'),
 165: Int64Index([8304, 15957, 18552], dtype='int64'),
 166: Int64Index([10309], dtype='int64'),
 167: Int64Index([9443], dtype='int64'),
 168: Int64Index([8305], dtype='int64'),
 169: Int64Index([8306, 15958, 18553, 20450], dtype='int64'),
 170: Int64Index([9677], dtype='int64'),
 171: Int64Index([8307, 15959, 18554, 20451], dtype='int64'),
 172: Int64Index([9678], dtype='int64'),
 173: Int64Index([8640, 16127], dtype='int64'),
 174: Int64Index([4917, 15129], dtype='int64'),
 175: Int64Index([1280], dtype='int64'),
 176: Int64Index([1282], dtype='int64'),
 177: Int64Index([4919, 15131], dtype='int64'),
 178: Int64Index([9923, 16753, 19178], dtype='int64'),
 179: Int64Index([3396], dtype='int64'),
 180: Int64Index([4926], dtype='int64'),
 181: Int64Index([9924], dtype='int64'),
 183: Int64Index([3399], dtype='int64'),
 184: Int64Index([9925], dtype='int64'),
 185: Int64Index([3403], dtype='int64'),
 186: Int64Index([664, 14159], dtype='int64'),
 187: Int64Index([262], dtype='int64'),
 188: Int64Index([5636, 15300], dtype='int64'),
 189: Int64Index([9926, 16754, 19179, 20868], dtype='int64'),
 190: Int64Index([3404], dtype='int64'),
 191: Int64Index([9927, 16755, 19180, 20869], dtype='int64'),
 192: Int64Index([3405], dtype='int64'),
 193: Int64Index([10301, 16910], dtype='int64'),
 194: Int64Index([2894, 14597], dtype='int64'),
 195: Int64Index([9928, 16756, 19181], dtype='int64'),
 196: Int64Index([8946, 16306], dtype='int64'),
 197: Int64Index([3407], dtype='int64'),
 198: Int64Index([8299], dtype='int64'),
 199: Int64Index([3409], dtype='int64'),
 200: Int64Index([3245, 14675], dtype='int64'),
 201: Int64Index([3247], dtype='int64'),
 202: Int64Index([3249, 14676], dtype='int64'),
 203: Int64Index([9762, 16686], dtype='int64'),
 204: Int64Index([9177, 16430, 18916], dtype='int64'),
 205: Int64Index([9763, 16687], dtype='int64'),
 206: Int64Index([9179, 16432, 18917, 20679], dtype='int64'),
 207: Int64Index([488, 14106], dtype='int64'),
 208: Int64Index([9764], dtype='int64'),
 209: Int64Index([9180, 16433, 18918, 20680], dtype='int64'),
 210: Int64Index([9005, 16343, 18844, 20644], dtype='int64'),
 211: Int64Index([6180], dtype='int64'),
 212: Int64Index([168], dtype='int64'),
 213: Int64Index([524, 14129], dtype='int64'),
 214: Int64Index([5858], dtype='int64'),
 215: Int64Index([9765], dtype='int64'),
 216: Int64Index([9181, 16434], dtype='int64'),
 217: Int64Index([8936, 16299, 18812], dtype='int64'),
 218: Int64Index([6181], dtype='int64'),
 219: Int64Index([526, 14130], dtype='int64'),
 220: Int64Index([5859], dtype='int64'),
 221: Int64Index([9766], dtype='int64'),
 222: Int64Index([9182, 16435], dtype='int64'),
 223: Int64Index([8937], dtype='int64'),
 225: Int64Index([5860], dtype='int64'),
 226: Int64Index([9916, 16749], dtype='int64'),
 227: Int64Index([9767, 16688], dtype='int64'),
 228: Int64Index([10542], dtype='int64'),
 229: Int64Index([8938], dtype='int64'),
 230: Int64Index([8156, 15890, 18499, 20406], dtype='int64'),
 231: Int64Index([6185], dtype='int64'),
 232: Int64Index([5792], dtype='int64'),
 233: Int64Index([5864], dtype='int64'),
 234: Int64Index([8939], dtype='int64'),
 235: Int64Index([8157, 15891, 18500, 20407], dtype='int64'),
 236: Int64Index([7385], dtype='int64'),
 237: Int64Index([6187], dtype='int64'),
 238: Int64Index([158], dtype='int64'),
 239: Int64Index([2567], dtype='int64'),
 240: Int64Index([5793, 15338, 18324], dtype='int64'),
 241: Int64Index([8940, 16300, 18813], dtype='int64'),
 242: Int64Index([8159, 15892], dtype='int64'),
 243: Int64Index([7387], dtype='int64'),
 244: Int64Index([6188], dtype='int64'),
 245: Int64Index([2568], dtype='int64'),
 246: Int64Index([8160, 15893], dtype='int64'),
 247: Int64Index([6189], dtype='int64'),
 248: Int64Index([2569], dtype='int64'),
 249: Int64Index([8161, 15894, 18501, 20408], dtype='int64'),
 250: Int64Index([2570], dtype='int64'),
 251: Int64Index([1224], dtype='int64'),
 252: Int64Index([411, 14058], dtype='int64'),
 253: Int64Index([5487, 15267, 18318], dtype='int64'),
 254: Int64Index([2571], dtype='int64'),
 255: Int64Index([1225, 14324], dtype='int64'),
 256: Int64Index([5488], dtype='int64'),
 257: Int64Index([1227], dtype='int64'),
 258: Int64Index([5489], dtype='int64'),
 259: Int64Index([9810], dtype='int64'),
 260: Int64Index([5490, 15268], dtype='int64'),
 261: Int64Index([1228, 14326], dtype='int64'),
 262: Int64Index([9811, 16691, 19128, 20830], dtype='int64'),
 263: Int64Index([9173], dtype='int64'),
 264: Int64Index([7145, 15651], dtype='int64'),
 265: Int64Index([5241, 15210], dtype='int64'),
 266: Int64Index([1230], dtype='int64'),
 267: Int64Index([4026], dtype='int64'),
 269: Int64Index([9812], dtype='int64'),
 270: Int64Index([7146], dtype='int64'),
 271: Int64Index([4028], dtype='int64'),
 272: Int64Index([5492, 15270], dtype='int64'),
 273: Int64Index([135], dtype='int64'),
 274: Int64Index([7147], dtype='int64'),
 275: Int64Index([4032], dtype='int64'),
 276: Int64Index([5494], dtype='int64'),
 277: Int64Index([7148, 15652], dtype='int64'),
 278: Int64Index([5495, 15271], dtype='int64'),
 279: Int64Index([7149], dtype='int64'),
 280: Int64Index([5496], dtype='int64'),
 281: Int64Index([8155], dtype='int64'),
 282: Int64Index([7150], dtype='int64'),
 283: Int64Index([3229, 14671], dtype='int64'),
 284: Int64Index([295], dtype='int64'),
 285: Int64Index([7151, 15653], dtype='int64'),
 286: Int64Index([3232], dtype='int64'),
 287: Int64Index([5614], dtype='int64'),
 288: Int64Index([7153], dtype='int64'),
 289: Int64Index([3233], dtype='int64'),
 290: Int64Index([10203], dtype='int64'),
 291: Int64Index([9059, 16367, 18864], dtype='int64'),
 292: Int64Index([7154, 15654], dtype='int64'),
 293: Int64Index([3235, 14672], dtype='int64'),
 294: Int64Index([4014], dtype='int64'),
 295: Int64Index([9062, 16368, 18865, 20653], dtype='int64'),
 296: Int64Index([7155], dtype='int64'),
 297: Int64Index([6654, 15539], dtype='int64'),
 298: Int64Index([4015, 14860, 18257], dtype='int64'),
 299: Int64Index([7156], dtype='int64'),
 300: Int64Index([3238], dtype='int64'),
 301: Int64Index([4215, 14913, 18274], dtype='int64'),
 302: Int64Index([9063, 16369, 18866], dtype='int64'),
 303: Int64Index([6656], dtype='int64'),
 304: Int64Index([4017], dtype='int64'),
 305: Int64Index([4], dtype='int64'),
 306: Int64Index([3239, 14673], dtype='int64'),
 307: Int64Index([7157], dtype='int64'),
 308: Int64Index([6657], dtype='int64'),
 309: Int64Index([6406], dtype='int64'),
 310: Int64Index([6422], dtype='int64'),
 311: Int64Index([3241], dtype='int64'),
 312: Int64Index([4018], dtype='int64'),
 313: Int64Index([9963], dtype='int64'),
 314: Int64Index([9066, 16371, 18867], dtype='int64'),
 315: Int64Index([7158, 15655], dtype='int64'),
 316: Int64Index([6658, 15540], dtype='int64'),
 317: Int64Index([4019, 14861, 18258], dtype='int64'),
 318: Int64Index([3243], dtype='int64'),
 319: Int64Index([9964], dtype='int64'),
 320: Int64Index([9067], dtype='int64'),
 321: Int64Index([8492], dtype='int64'),
 322: Int64Index([6659], dtype='int64'),
 323: Int64Index([3244], dtype='int64'),
 324: Int64Index([4020, 14862, 18259, 20314], dtype='int64'),
 325: Int64Index([9966, 16771], dtype='int64'),
 326: Int64Index([8493, 16056, 18631, 20507], dtype='int64'),
 327: Int64Index([7139], dtype='int64'),
 328: Int64Index([6660, 15541], dtype='int64'),
 329: Int64Index([4022, 14863], dtype='int64'),
 330: Int64Index([8494, 16057, 18632, 20508, 21442], dtype='int64'),
 332: Int64Index([6661, 15542], dtype='int64'),
 333: Int64Index([4024], dtype='int64'),
 334: Int64Index([8495], dtype='int64'),
 335: Int64Index([10760], dtype='int64'),
 336: Int64Index([6662, 15543], dtype='int64'),
 337: Int64Index([8733, 16176, 18717, 20564], dtype='int64'),
 338: Int64Index([10761, 17113, 19467], dtype='int64'),
 339: Int64Index([10742], dtype='int64'),
 340: Int64Index([6663, 15544], dtype='int64'),
 341: Int64Index([5947], dtype='int64'),
 342: Int64Index([10105], dtype='int64'),
 343: Int64Index([8734, 16177, 18718, 20565], dtype='int64'),
 344: Int64Index([10743], dtype='int64'),
 345: Int64Index([10762, 17114, 19468], dtype='int64'),
 346: Int64Index([8736, 16179, 18719, 20566], dtype='int64'),
 347: Int64Index([10763], dtype='int64'),
 348: Int64Index([1526], dtype='int64'),
 349: Int64Index([110], dtype='int64'),
 350: Int64Index([8738, 16180, 18720, 20567], dtype='int64'),
 351: Int64Index([10766, 17115, 19469, 21045], dtype='int64'),
 352: Int64Index([10126, 16847, 19250, 20908], dtype='int64'),
 353: Int64Index([1525], dtype='int64'),
 354: Int64Index([8739], dtype='int64'),
 355: Int64Index([10767, 17116, 19470, 21046], dtype='int64'),
 356: Int64Index([10128, 16848, 19251, 20909], dtype='int64'),
 357: Int64Index([1528], dtype='int64'),
 358: Int64Index([9058, 16366], dtype='int64'),
 359: Int64Index([8740, 16181, 18721, 20568], dtype='int64'),
 360: Int64Index([10130, 16849, 19252], dtype='int64'),
 361: Int64Index([1527], dtype='int64'),
 362: Int64Index([6648], dtype='int64'),
 363: Int64Index([10131], dtype='int64'),
 364: Int64Index([902, 14242], dtype='int64'),
 365: Int64Index([1530], dtype='int64'),
 366: Int64Index([5657], dtype='int64'),
 367: Int64Index([903], dtype='int64'),
 368: Int64Index([1529], dtype='int64'),
 369: Int64Index([10132, 16850, 19253], dtype='int64'),
 370: Int64Index([1531], dtype='int64'),
 371: Int64Index([904], dtype='int64'),
 372: Int64Index([8004, 15845, 18457], dtype='int64'),
 373: Int64Index([1532], dtype='int64'),
 374: Int64Index([905], dtype='int64'),
 375: Int64Index([8005], dtype='int64'),
 376: Int64Index([4825], dtype='int64'),
 377: Int64Index([906], dtype='int64'),
 378: Int64Index([269], dtype='int64'),
 379: Int64Index([1533], dtype='int64'),
 380: Int64Index([8006, 15846], dtype='int64'),
 381: Int64Index([907, 14243], dtype='int64'),
 382: Int64Index([2032], dtype='int64'),
 383: Int64Index([1534], dtype='int64'),
 384: Int64Index([8007, 15847, 18458], dtype='int64'),
 385: Int64Index([910, 14244], dtype='int64'),
 386: Int64Index([4586, 15037], dtype='int64'),
 387: Int64Index([2033], dtype='int64'),
 388: Int64Index([1535], dtype='int64'),
 389: Int64Index([9272], dtype='int64'),
 390: Int64Index([8008], dtype='int64'),
 391: Int64Index([4590, 15039], dtype='int64'),
 392: Int64Index([911], dtype='int64'),
 393: Int64Index([1536], dtype='int64'),
 394: Int64Index([2034], dtype='int64'),
 396: Int64Index([8009, 15848, 18459], dtype='int64'),
 397: Int64Index([1537], dtype='int64'),
 398: Int64Index([2035], dtype='int64'),
 399: Int64Index([8010], dtype='int64'),
 400: Int64Index([2036], dtype='int64'),
 401: Int64Index([5242], dtype='int64'),
 402: Int64Index([646, 14149], dtype='int64'),
 403: Int64Index([1538], dtype='int64'),
 404: Int64Index([8012, 15849, 18460, 20378], dtype='int64'),
 405: Int64Index([5245], dtype='int64'),
 406: Int64Index([1540], dtype='int64'),
 407: Int64Index([2038], dtype='int64'),
 408: Int64Index([8013, 15850, 18461, 20379], dtype='int64'),
 409: Int64Index([1539], dtype='int64'),
 410: Int64Index([2040], dtype='int64'),
 411: Int64Index([10118, 16843], dtype='int64'),
 412: Int64Index([2041], dtype='int64'),
 413: Int64Index([1541], dtype='int64'),
 414: Int64Index([10119], dtype='int64'),
 415: Int64Index([223], dtype='int64'),
 416: Int64Index([535, 14135], dtype='int64'),
 417: Int64Index([1542], dtype='int64'),
 418: Int64Index([10124], dtype='int64'),
 419: Int64Index([6688], dtype='int64'),
 420: Int64Index([1543], dtype='int64'),
 421: Int64Index([53], dtype='int64'),
 422: Int64Index([1544], dtype='int64'),
 423: Int64Index([1545], dtype='int64'),
 424: Int64Index([2687], dtype='int64'),
 425: Int64Index([1546], dtype='int64'),
 426: Int64Index([2688], dtype='int64'),
 427: Int64Index([1547], dtype='int64'),
 428: Int64Index([10001, 16782, 19199, 20878], dtype='int64'),
 429: Int64Index([2691, 14555], dtype='int64'),
 430: Int64Index([10002, 16783, 19200, 20879], dtype='int64'),
 431: Int64Index([1549], dtype='int64'),
 432: Int64Index([2693], dtype='int64'),
 433: Int64Index([9372], dtype='int64'),
 434: Int64Index([10003, 16784, 19201, 20880], dtype='int64'),
 435: Int64Index([419, 14066], dtype='int64'),
 436: Int64Index([2694], dtype='int64'),
 437: Int64Index([150], dtype='int64'),
 438: Int64Index([10004, 16785, 19202, 20881], dtype='int64'),
 439: Int64Index([8678, 16154], dtype='int64'),
 440: Int64Index([8679], dtype='int64'),
 441: Int64Index([4477, 14989, 18288], dtype='int64'),
 442: Int64Index([10262], dtype='int64'),
 443: Int64Index([8680, 16155], dtype='int64'),
 444: Int64Index([7839], dtype='int64'),
 445: Int64Index([4478], dtype='int64'),
 446: Int64Index([10254], dtype='int64'),

Now, if we want to know the number of performances per program we can simply call `DataFrameGroupBy.size()`

In [ ]:
concerts_grouped_by_ProgramID.size()

The same result but using the all the operations together

In [ ]:
concerts.groupby('ProgramID').size()

With the operation above we obtain a Dataframe with the number of performances per `ProgramID`. If we want to know the most popular ones we need to use the `pd.DataFrame.nlargest()`

In [ ]:
concerts.groupby('ProgramID').size().nlargest()

We use `GroupBy.size()` to count the number of elements in each group. A list of available methods:
* `mean()`
* `sum()`
* `size()`
* `count()`
* `std()`
* `var()`
* `sem()`
* `describe()`
* `first()`
* `last()`
* `nth()`
* `min()`
* `max()`.

Alternatively, we can use `GroupBy.agg()` as a more general method. Check out the [docs](http://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.core.groupby.DataFrameGroupBy.agg.html).

You could even define your own aggregation function using the lambda nomenclature, we will see an example of it in the transformation topic.

Let's now imagine that we want to know when it was the first performance of each program.
We start by `group-by` the shows by `ProgramID` and then, for each group we take the `min` of the Date column.

In [19]:

concerts.groupby('ProgramID').Date.min()

ProgramID
1        1897-02-05T05:00:00+00:00
2        1916-12-03T05:00:00+00:00
3        1916-12-06T05:00:00+00:00
4        1916-12-07T05:00:00+00:00
5        1983-09-14T04:00:00+00:00
6        1916-12-09T05:00:00+00:00
7        1983-09-15T04:00:00+00:00
8        1983-08-06T04:00:00+00:00
9        1977-03-05T05:00:00+00:00
10       1957-12-01T05:00:00+00:00
11       1916-12-10T05:00:00+00:00
12       1983-09-22T04:00:00+00:00
13       1983-07-27T04:00:00+00:00
14       1977-03-14T05:00:00+00:00
15       1957-12-03T05:00:00+00:00
16       1874-01-17T05:00:00+00:00
17       1930-04-03T05:00:00+00:00
18       1916-12-11T05:00:00+00:00
19       1983-08-05T04:00:00+00:00
20       1983-09-29T04:00:00+00:00
21       1977-03-23T05:00:00+00:00
22       1957-12-05T05:00:00+00:00
24       1916-12-13T05:00:00+00:00
25       1983-08-02T04:00:00+00:00
26       1987-05-02T04:00:00+00:00
27       1957-12-08T05:00:00+00:00
28       1916-12-14T05:00:00+00:00
29       1930-04-05T05:00:00+00:00
30       1987-05-05T04:00:00+00:00
31       1967-08-01T04:00:00+00:00
                   ...
14159    2017-01-19T05:00:00+00:00
14160    2017-01-19T05:00:00+00:00
14161    2017-01-20T05:00:00+00:00
14162    2017-01-20T05:00:00+00:00
14163    2017-01-09T05:00:00+00:00
14164    2015-01-21T05:00:00+00:00
14165    2017-01-19T05:00:00+00:00
14166    2017-01-29T05:00:00+00:00
14168    2017-02-09T05:00:00+00:00
14169    2017-06-13T04:00:00+00:00
14170    2015-11-04T05:00:00+00:00
14171    2016-04-04T04:00:00+00:00
14172    2017-01-18T05:00:00+00:00
14173    2017-01-20T05:00:00+00:00
14174    2017-03-27T04:00:00+00:00
14175    2017-03-30T04:00:00+00:00
14176    2017-04-01T04:00:00+00:00
14177    2017-02-05T05:00:00+00:00
14178    2017-05-02T04:00:00+00:00
14179    2017-06-10T04:00:00+00:00
14180    2017-06-09T04:00:00+00:00
14181    2017-05-20T04:00:00+00:00
14182    2017-06-18T04:00:00+00:00
14189    2017-06-24T04:00:00+00:00
14190    2016-11-10T05:00:00+00:00
14191    2016-12-11T05:00:00+00:00
14192    2017-01-15T05:00:00+00:00
14193    2017-02-03T05:00:00+00:00
14194    2017-03-13T04:00:00+00:00
14195    2017-04-18T04:00:00+00:00
Name: Date, Length: 13932, dtype: object

And if we want to know when it was the last performance?

In [ ]:
concerts.groupby('ProgramID').Date.max()

**Transformation**

The inherent difference between aggregation and transformation is that the later returns an object the same size as the original input.

We don't have an excellent example in our dataset, so let's use the [Iris](https://archive.ics.uci.edu/ml/datasets/iris) dataset to exemplify a possible use case.

In [ ]:
iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df = df.assign(Target=iris.target)
df.head()

Now, imagine that we want to standardize the data, but using the statistics for each group:
* We take the mean and the standard deviation *inside each group*
* We want to standardize each value according to that.

We implement it as a lambda function, that will be applied to each group separately.

In [ ]:
zscore = lambda x: (x - x.mean()) / x.std()

df.groupby('Target').transform(zscore).head()

The downside is that, since we are returning the entire dataframe, it can't return `Target` as the index, so we lose the column.

Let's make sure we got this right.

In [ ]:
df_transformed = df.groupby('Target').transform(zscore)

df_transformed.groupby(df['Target']).agg(['mean', 'std'])

We did it! Zero mean and standard deviation equal to one *inside each group*.

Now, if this use case doesn't ring a bell, think about replacing missing values with the group mean, for example. Useful, right?

**Filtration**

The method `DataFrameGroupBy.filter()` provides a convenient way to filter out elements that belong to underrepresented groups.

In [ ]:
concerts.groupby('ProgramID').filter(lambda x: x.shape[0] > 15).head()

It returns a subset of the original dataframe, depending on a function applied to the group as a whole.

### 1.2.4 Method chaining

Now we know about some of the most common individual transformations we can use. But how can we combine them?

Data transformation is a pipeline, i.e., some sequential transformations, *chained* together.

This chaining means that each transformation returns an object that will be consumed by the next one, and so on, in a pre-defined order.

As we've seen, a familiar syntax is to declare intermediate variables for each output, used as input to the next function.

As an example, let us define a simple function that make the subset of a dataframe based on a mask

In [ ]:
def subset(df, mask):
    return df[mask]

In [ ]:
mask = works['Interval'].isnull()
df_no_intervals = subset(works,mask)

df_exclude_minor_composers = df_no_intervals.groupby('ComposerName').filter(lambda x: x.shape[0] > 10)

df_work_related = df_exclude_minor_composers.filter(items=work_related_columns)
df_work_related_no_movement = df_work_related.drop(columns='Movement')
df_work_related_no_movement_unique = df_work_related_no_movement.drop_duplicates()

works_per_composer = df_work_related_no_movement_unique.groupby('ComposerName').size()
works_per_composer_sorted = works_per_composer.nlargest()
works_per_composer_sorted

These declarations are syntactic sugar: they make it easier to read and express confusing things such as data pipelines. Some downsides:
* We need to create an extra variable per intermediate step
* Cognitive burden of naming each variable and keeping them in mind
* They make the code less fluid
* They make it harder to visualize the whole picture of what your program (or Notebook) is doing
* They are error-prone and heavily reliant on the state, which is dangerous as we've seen.

What if there was an alternative?

Method chaining allows invoking multiple method calls chained together in a single statement, each receiving and returning an object.

This syntax has always been possible with Pandas, but more and more methods and being added that (try to guess it!):
* Receive a dataframe
* Return a transformed dataframe.

In [40]:
no_intervals = works['Interval'].isnull()
df_no_intervals = subset(works,mask)

df_work_related = df_no_intervals.filter(items=work_related_columns)

(df_work_related.groupby('ComposerName').filter(lambda x: x.shape[0] > 10)
                .drop(columns='Movement')
                .drop_duplicates()
                .groupby('ComposerName').size()
                .nlargest()
                .plot(kind='bar'));

NameError: name 'subset' is not defined

Code flows from top to bottom, and the function parameters are always near the function. 

Also, you eliminate an extra variable for each intermediate steps.

Now, explicitly naming things is good. Ideally, you want to chain functions that make sense together and encapsulate them in logically.

In [39]:
def get_top_5_composers(df):
    df = df.copy()
    
    no_intervals = df['Interval'].isnull()
    df = subset(df, no_intervals)
    
    work_related_columns = ['ComposerName', 'WorkTitle', 'Movement']
    
    df = (df.filter(work_related_columns)
            .groupby('ComposerName').filter(lambda x: x.shape[0] > 10)
            .drop(columns='Movement')
            .drop_duplicates()
            .groupby('ComposerName').size()
            .nlargest())
    return df

top_5_composers = get_top_5_composers(works)
top_5_composers

NameError: name 'subset' is not defined

Another drawback to excessively long chains is that debugging is harder, as there no intermediate values to inspect.

**Segregate your code as to avoid long chains and keep only together what belongs together.**

(In case of doubt, read [The Zen of Python](https://www.python.org/dev/peps/pep-0020/) out loud ten times.)

### 1.2.5 Custom methods and pipes

Now, for the final trick.

The function `subset()` has the exact signature we want, again:
* It receives a dataframe
* It return a transformed dataframe.

What if Pandas had a way to include such functions in pipelines? Meet `df.pipe()`!

The method `df.pipe()` allows us to include user-defined functions in method chains (aka pipelines).

It works like this.

In [ ]:
(df_work_related.pipe(subset, no_intervals)
                .filter(items=work_related_columns)
                .groupby('ComposerName').filter(lambda x: x.shape[0] > 10)
                .drop(columns='Movement')
                .drop_duplicates()
                .groupby('ComposerName').size()
                .nlargest()
                .plot(kind='bar'));

So, this should work.

In [38]:
def get_top_5_composers(df):
    no_intervals = df['Interval'].isnull()
    work_related_columns = ['ComposerName', 'WorkTitle', 'Movement']
    
    df = df.copy()
    df = (df.pipe(subset, no_intervals)
            .filter(items=work_related_columns)
            .groupby('ComposerName').filter(lambda x: x.shape[0] > 10)
            .drop(columns='Movement')
            .drop_duplicates()
            .groupby('ComposerName').size()
            .nlargest())
    
    return df

top_5_composers = get_top_5_composers(works)
top_5_composers

NameError: name 'subset' is not defined

And it does!

Now, we have all the tools we need to build robust data transformation pipelines in Pandas.

In the next Notebook, you will learn how to combine dataframes.